### ISSUE TITLE
sftp with root access does not work

### ISSUE THREAD

**Issue by nicexe** [linuxserver/docker-openssh-server#14]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
set a UID and GID of 0 to a user and have access to files owned by 0

## Current Behavior
the server says the password is wrong

## Steps to Reproduce

1. set a user with uid and gid as 0
2. attempt to login: ssh notroot@host -p 2222
3. get error `Permission denied (publickey,password,keyboard-interactive).`

## Environment
**OS:**      Debian 10
**CPU architecture:** x86_64      
**How docker service was installed:**      official docker-ce repository for debian

## Command used to create docker container (run/create/compose/screenshot)

`docker-compose up -d`
```yaml
  sftp:
    image: linuxserver/openssh-server:latest
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=pass
      - USER_NAME=notroot
    volumes:
      - './files:/files'
    ports:
      - "2222:2222"
    restart: unless-stopped
```

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    0
User gid:    0
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 50-config: executing...
User name is set to notroot
Sudo is disabled.
ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519
User/password ssh access is enabled.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
