### ISSUE TITLE
how to set 'sshd_conf' config file

### ISSUE THREAD

**Issue by Art-Man** [linuxserver/docker-openssh-server#22]
## docker yaml
```yaml
  openssh-server:
    image: linuxserver/openssh-server
    container_name: openssh-server
    hostname: openssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=test
      - USER_NAME=test
    volumes:
      - ./sshd/sshd_config:/etc/ssh/sshd_config:rw
```
------------

I wanna chan fellow at /etc/ssh/sshd_config to open Forwarding settings;
```
#AllowAgentForwarding yes
AllowAgentForwarding yes
# Feel free to re-enable these if your use case requires them.
AllowTcpForwarding yes
#AllowTcpForwarding no
GatewayPorts yes
#GatewayPorts no
X11Forwarding yes
#X11Forwarding no
```

------------------------------

## Docker logs

[cont-init.d] 50-config: executing... 
User name is set to lds
Sudo is disabled.
sed: can't move '/etc/ssh/sshd_configkKOoLI' to '/etc/ssh/sshd_config': Resource busy
rm: cannot remove '/etc/ssh/sshd_config': Resource busy
ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519 
sed: can't move '/etc/ssh/sshd_configoHFmgH' to '/etc/ssh/sshd_config': Resource busy
sed: can't move '/etc/ssh/sshd_configLOHJpF' to '/etc/ssh/sshd_config': Resource busy
User/password ssh access is enabled.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.

**Comment by aptalca** [comment]
Why?

You don't need to map the whole file. Use a custom script to sed it if you need to: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by Art-Man** [comment]
@aptalca  think you,
I'll try to use  Custom Scripts;
## first:mkdir   **/config/custom-cont-init.d** 
```yaml
    volumes:
      - ./sshd/config:/config:rw
```
and add the fellow script to it;
```shell script
#!/bin/bash
# set -e
sed -i 's/#AllowAgentForwarding yes/AllowAgentForwarding yes/g' /etc/ssh/sshd_config
sed -i 's/AllowTcpForwarding no/AllowTcpForwarding yes/g' /etc/ssh/sshd_config
sed -i 's/GatewayPorts no/GatewayPorts yes/g' /etc/ssh/sshd_config
sed -i 's/X11Forwarding no/X11Forwarding yes/g' /etc/ssh/sshd_config

```

**Comment by Art-Man** [comment]
It works, think you! @aptalca

**Comment by nikoudel** [comment]
That's exactly what I needed, thank you @Art-Man!

Perhaps it would make sense to add this to documentation @aptalca? Port forwarding is probably pretty common scenario...

**Comment by aptalca** [comment]
Customization is already documented in the readme.
There is also a mod for ssh tunnel with port forwarding: https://github.com/linuxserver/docker-mods/tree/openssh-server-ssh-tunnel

**Comment by nikoudel** [comment]
>Customization is already documented in the readme.

Yeah, I can see it now - the word "customization" is mentioned in two places. But I'm pretty sure a random user ending up on the page from a goole search like "docker hub openssh" will have hard time connecting that word with his goal of setting up a tunnel ;)

> There is also a mod for ssh tunnel with port forwarding

That's a nice one, thank you!

**Comment by krutovgerman** [comment]
> and add the fellow script to it;
> 
> ```shell
> #!/bin/bash
> # set -e
> sed -i 's/#AllowAgentForwarding yes/AllowAgentForwarding yes/g' /etc/ssh/sshd_config
> sed -i 's/AllowTcpForwarding no/AllowTcpForwarding yes/g' /etc/ssh/sshd_config
> sed -i 's/GatewayPorts no/GatewayPorts yes/g' /etc/ssh/sshd_config
> sed -i 's/X11Forwarding no/X11Forwarding yes/g' /etc/ssh/sshd_config
> ```

Thank you!!! It works :)

**Comment by quarkcore** [comment]
sshd_config seems to be a directory by default!? seems strange but:

```
2023-11-13 23:44:19 User name is set to ****
2023-11-13 23:44:19 sudo is enabled without password.
2023-11-13 23:44:19 sshd is listening on port 2222
2023-11-13 23:44:19 User/password ssh access is disabled.
2023-11-13 23:44:19 Public key from file added
2023-11-13 23:44:19 [custom-init] No custom files found, skipping...
2023-11-13 23:44:19 cp: cannot overwrite directory '/config/ssh_host_keys/sshd_config' with non-directory
2023-11-13 23:44:19 sed: can't move '/etc/ssh/sshd_configpgnDkA' to '/etc/ssh/sshd_config': Is a directory
2023-11-13 23:44:19 sed: can't move '/etc/ssh/sshd_configblIckA' to '/etc/ssh/sshd_config': Is a directory
2023-11-13 23:44:19 sed: can't move '/etc/ssh/sshd_configEBpClA' to '/etc/ssh/sshd_config': Is a directory
2023-11-13 23:44:19 sed: can't move '/etc/ssh/sshd_configBNgCmA' to '/etc/ssh/sshd_config': Is a directory
```

directory is auto created after container start? seems to prevent me from logging in. changing it to file on mounted host volume fails also obviously.. 

here is the config part of my `docker-compose.yml`:
```
sshtunnel:
    restart: always
    image: ghcr.io/linuxserver/openssh-server
    container_name: sshtunnel
    ports:
      - 2222:2222
    volumes:
      - ~/.ssh/id_rsa.pub:/etc/tunnel/id_rsa.pub
      - ./openssh/sshd_config:/config/ssh_host_keys/sshd_config
    environment:
      - PUBLIC_KEY_FILE=/etc/tunnel/id_rsa.pub
      - USER_NAME=proxy
      - SUDO_ACCESS=true
    networks:
      - proxy
```

Container is running after `compose up`

but if i try ssh into it with: `ssh -p 2222 proxy@localhost -v`. i get a kex_exchange_identification error.
```
OpenSSH_9.4p1, LibreSSL 3.3.6
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to localhost port 2222.
debug1: Connection established.
debug1: identity file ****/.ssh/id_rsa type 0
debug1: identity file ****/.ssh/id_rsa-cert type -1
debug1: identity file ****/.ssh/id_ecdsa type -1

[...]

debug1: identity file ****/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.4
kex_exchange_identification: read: Connection reset by peer
Connection reset by ::1 port 2222
```

any ideas?
