### ISSUE TITLE
Permission denied when using custom keys

### ISSUE THREAD

**Issue by mihaigalos** [linuxserver/docker-openssh-server#46]
Using custom-generated ssh keys and ssh-ing into a running docker instance yields "Permission denied (publickey,keyboard-interactive)".
------------------------------

## Expected Behavior
ssh works.

## Steps to Reproduce
1. Started container, attached to it:
```
$ cat docker-compose.yaml
---
version: "2.1"
services:
  openssh-server:
    image: ghcr.io/linuxserver/openssh-server
    hostname: openssh-server #optional
    environment:
      - HISTFILE=/root/.history_make_shell
      - PASSWORD_ACCESS=false #optional
      - PGID=1000
      - PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
      - PUBLIC_KEY_FILE=/path/to/file #optional
      - PUBLIC_KEY=AAAAB3NzaC1yc2EAAAADAQABAAABgQC/xsm9kvCI00mYVGIpppF37IQlV361wMfEgDdgno+q8Pz11RpmaDcZ3stvQ6CFYpypbkBOiuEo2sW0kYPmaNR91V3C20woR0vwi9DwlkZuYCt/w6kW4wJG8XjCKYu7tQ/Lrzoa28wH+mBflZAmVJu/0ua7MhMFw1AqvQlgd+uwO0LOwWDGTrE5Odds3pBc8XYji9Xjww8tzTT13EwpSLxxrU/Ee5wPWk5bv2IRs6hYS9mympd8+ysiZnxRSs0j3hXRhrru0IocSa8pEtGfCCT0cGl5z77SIEs1wOgRhu9JigkIr/RLjcudpcXm4TmuCVkBCsxz2XZ5lQx2tAKdkboSaBriaw6Bl1V0Kl9YDSoAjx5wxMy4ORhjXJ6pdvSMHnvcWKP9wO+mE+Mscl/VnmOlErKwCIIhOBs/IbqgvcQdlZ3PbtzeJQQDnr+DRs4GN6AbWk1UZecKgLLnT8Yl+hrYtD9RAcrBvHKKpp7HO/B7b9YfOmiSm6fb3VfYGq5MfM8= #optional
      - PUID=1000
      - SUDO_ACCESS=false #optional
      - TZ=Europe/London
      - USER_NAME=root #optional
        #- USER_PASSWORD_FILE=/path/to/file #optional
        #- USER_PASSWORD=password #optional
    volumes:
      - /path/to/appdata/config:/config
      - ~/.history_make_shell:/root/.history_make_shell
      - $PWD/ssh_server/keys:/root/.ssh:ro
      - /tmp/tmp.DJpiNS9kqv:/tmp
    ports:
      - 2222:2222
    restart: unless-stopped

$ docker exec -it 0e804ca039c7 /bin/bash
```
2. Generated ssh keys in mounted volume:
```bash
# ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/root/.ssh/id_rsa): /tmp/id_rsa
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /tmp/id_rsa
Your public key has been saved in /tmp/id_rsa.pub
The key fingerprint is:
SHA256:lCLV4YJP3z+Q8RnBtvH4SLmiXbtT5I1JOnRFKOls8Qw
```

3. Copied public key to the `docker-compose.yaml` `PUBLIC_KEY` env var.
4. Tried to ssh using them:
```bash
$ ssh -i /tmp/tmp.DJpiNS9kqv/id_rsa -p 2222 root@127.0.0.1
root@127.0.0.1: Permission denied (publickey,keyboard-interactive).
```

**Comment by tobbenb** [comment]
You should not have the PUBLIC_KEY_DIR and PUBLIC_KEY_FILE when not using them. Remove them and see if that fixes your issue.

**Comment by mihaigalos** [comment]
No, that does not solve the problem.

**Comment by mihaigalos** [comment]
If I attach to the running docker, the `/config/.ssh/authorized_keys` contains the correct key however:
```bash
root@openssh-server:/config/.ssh# cat authorized_keys 
AAAAB3NzaC1yc2EAAAADAQABAAABgQC/xsm9kvCI00mYVGIpppF37IQlV361wMfEgDdgno+q8Pz11RpmaDcZ3stvQ6CFYpypbkBOiuEo2sW0kYPmaNR91V3C20woR0vwi9DwlkZuYCt/w6kW4wJG8XjCKYu7tQ/Lrzoa28wH+mBflZAmVJu/0ua7MhMFw1AqvQlgd+uwO0LOwWDGTrE5Odds3pBc8XYji9Xjww8tzTT13EwpSLxxrU/Ee5wPWk5bv2IRs6hYS9mympd8+ysiZnxRSs0j3hXRhrru0IocSa8pEtGfCCT0cGl5z77SIEs1wOgRhu9JigkIr/RLjcudpcXm4TmuCVkBCsxz2XZ5lQx2tAKdkboSaBriaw6Bl1V0Kl9YDSoAjx5wxMy4ORhjXJ6pdvSMHnvcWKP9wO+mE+Mscl/VnmOlErKwCIIhOBs/IbqgvcQdlZ3PbtzeJQQDnr+DRs4GN6AbWk1UZecKgLLnT8Yl+hrYtD9RAcrBvHKKpp7HO/B7b9YfOmiSm6fb3VfYGq5MfM8=
```

**Comment by aptalca** [comment]
Don't use `root` as the username

**Comment by mihaigalos** [comment]
Thank you, that worked. Created a new user `dev`, generated ssh keys and used this `docker-compose.yaml`:
```yaml
---
version: "2.1"
services:
  openssh-server:
    image: ghcr.io/linuxserver/openssh-server
    hostname: openssh-server #optional
    environment:
      - HISTFILE=/root/.history_make_shell
      - PASSWORD_ACCESS=false #optional
      - PGID=1000
      - PUBLIC_KEY_FILE=/root/.ssh/id_ed25519.pub #optional
      - PUID=1000
      - SUDO_ACCESS=false #optional
      - TZ=Europe/London
      - USER_NAME=dev #optional
    volumes:
      - /path/to/appdata/config:/config
      - $PWD/keys/id_ed25519.pub:/root/.ssh/id_ed25519.pub
      - ~/.history_make_shell:/root/.history_make_shell
    ports:
      - 2222:2222
    restart: unless-stopped
```
And:
```bash
ssh -i keys/id_ed25519 -p 2222 dev@127.0.0.1                                                                                               mihai@galos 19/07/21 20:18:10
Welcome to OpenSSH Server

openssh-server:~$
```
