### ISSUE TITLE
openssh logs should not be accessible/removable by the user

### ISSUE THREAD

**Issue by jkirk** [linuxserver/docker-openssh-server#58]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I think it should not be possible for the ssh user to access and/or remove the openssh logs.

## Current Behavior

The user is able to access and remove the openssh logs.

## Steps to Reproduce

1. Log in to openssh-server
2. `rm -rf logs`

## Command used to create docker container (run/create/compose/screenshot)

```
% pwd                               
/srv/upload-ssh

% cat docker-compose.yml 
---
version: "2.1"
services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server
    container_name: openssh-server
    hostname: upload-ssh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=[SNIP]
      - USER_NAME=upload
    volumes:
      - /srv/upload-ssh/config:/config
    ports:
      - 2222:2222
      
% sudo docker-compose up
```
