### ISSUE TITLE
[BUG] confusing init-adduser behavior when picking a USER_NAME which collides with system user

### ISSUE THREAD

**Issue by chrishoage** [linuxserver/docker-openssh-server#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When specifying a USER_NAME and this user exists already  (e.g. listed in `/etc/passwd`) `usermod` fails with an error and `authorized_keys` is looked up from `/sbin` 

Currently this log is all that is present to signify there is an issue `usermod: user 'sync' already exists` 

I missed this log initially and only saw it once I found the issue after looking at the ssh debug logs. 

### Expected Behavior

An error should be raised and the container should exit 

### Steps To Reproduce

Set `USER_NAME` to one of these users (I was using `sync` which was producing the error)  

```
sync_server:~$ cat /etc/passwd
root:x:0:0:root:/root:/bin/sh
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/mail:/sbin/nologin
news:x:9:13:news:/usr/lib/news:/sbin/nologin
uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
ftp:x:21:21::/var/lib/ftp:/sbin/nologin
sshd:x:22:22:sshd:/dev/null:/sbin/nologin
games:x:35:35:games:/usr/games:/sbin/nologin
ntp:x:123:123:NTP:/var/empty:/sbin/nologin
guest:x:405:1000:guest:/dev/null:/sbin/nologin
nobody:x:65534:65534:nobody:/:/sbin/nologin
klogd:x:100:101:klogd:/dev/null:/sbin/nologin
```

### Environment

```markdown
- OS:Arch Linux
- How docker service was installed: pacman
```

### CPU architecture

x86-64

### Docker creation

docker compose up with SYNC_SSH_PUBLIC_KEY and SYNC_SSH_PUBLIC_KEY set in env

```yaml
services:
  sftp-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh_server
    hostname: sync_server
    environment:
      - PUID=1000
      - PGID=1000
      - PUBLIC_KEY=${SYNC_SSH_PUBLIC_KEY:?}
      - USER_NAME=sync
      - LOG_STDOUT=true
    volumes:
      - ./data:/data
      - ./ssh:/config
  alpine-test:
    image: alpine:latest
    container_name: alpine-test
    hostname: alpine-test
    volumes:
      - ./alpine:/config
    secrets:
      - source: sync_ssh_private_key
        mode: 0400
    command: ["tail", "-f", "/dev/null"]


secrets:
  sync_ssh_private_key:
    environment: SYNC_SSH_PRIVATE_KEY
```

### Container logs

```bash
❯ op run --env-file secrets.env -- docker compose up --force-recreate --always-recreate-deps
 Container alpine-test  Recreate
 Container openssh_server  Recreate
 Container openssh_server  Recreated
 Container alpine-test  Recreated
Attaching to alpine-test, openssh_server
openssh_server  | [migrations] started
openssh_server  | [migrations] no migrations found
openssh_server  | usermod: user 'sync' already exists
openssh_server  | ───────────────────────────────────────
openssh_server  |
openssh_server  |       ██╗     ███████╗██╗ ██████╗
openssh_server  |       ██║     ██╔════╝██║██╔═══██╗
openssh_server  |       ██║     ███████╗██║██║   ██║
openssh_server  |       ██║     ╚════██║██║██║   ██║
openssh_server  |       ███████╗███████║██║╚██████╔╝
openssh_server  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
openssh_server  |
openssh_server  |    Brought to you by linuxserver.io
openssh_server  | ───────────────────────────────────────
openssh_server  |
openssh_server  | To support LSIO projects visit:
openssh_server  | https://www.linuxserver.io/donate/
openssh_server  |
openssh_server  | ───────────────────────────────────────
openssh_server  | GID/UID
openssh_server  | ───────────────────────────────────────
openssh_server  |
openssh_server  | User UID:    1000
openssh_server  | User GID:    0
openssh_server  | ───────────────────────────────────────
openssh_server  | Linuxserver.io version: 9.7_p1-r4-ls172
openssh_server  | Build-date: 2024-11-10T18:48:18+00:00
openssh_server  | ───────────────────────────────────────
openssh_server  |
openssh_server  | User name is set to sync
openssh_server  | sudo is disabled.
openssh_server  | SSH host public key(s):
```

and the debug log that led me to understand what was happening 

```
openssh_server  | debug1: temporarily_use_uid: 1000/0 (e=1000/0)
openssh_server  | debug1: trying public key file /sbin/.ssh/authorized_keys
```

**Comment by antwal** [comment]
i have a similar problem with system user, i need use 'www-data' system user, but server not starting and change user gid:

docker compose:
```
version: "3.9"
services:
  wordpress:
    networks:
      - blackhole
    hostname: openssh-server
    container_name: openssh-server
    restart: unless-stopped
    image: lscr.io/linuxserver/openssh-server:latest
    ports:
      - "2222:2222"
    environment:
      - PUID=33
      - PGID=33
      - TZ=Europe/Rome
      - USER_NAME=www-data
    volumes:
      - /mnt/storage/openssh-server/config:/config
      - /mnt/storage/www-data/:/www-data/

networks:
  blackhole:
    name: container-net
    external: true
```

Docker Log:
```
[migrations] started
[migrations] no migrations found
groupmod: group 'www-data' already exists
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    33
User GID:    1001
───────────────────────────────────────
Linuxserver.io version: 9.7_p1-r4-ls179
Build-date: 2024-12-01T18:53:35+00:00
───────────────────────────────────────
    
User name is set to www-data
sudo is disabled.
SSH host public key(s):
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNgS4rePrIpw+uygy69sltdCQdXTzDtVujxBWA+wk/JY9lYmlDzu1KiV/GW1VFA5wC4AJTprxdJmnOAwDSaBamo= root@openssh-server
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAueSTsWJbt0ku3byZZ8iKqWhMpvVSfy14m7jDP0zJN6 root@openssh-server
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXmqMpNt9jtEND7PRyEvQJqZdLUMCrhs+iuUESeFskdjfqvpQH5hFRuIRX/wnct1HJn+aOKhpyvVWuRvlR/GhPqbHyMhHJjavwj4+uZ4hz2QBfxaqu6p6mhYurbFfHDly1ob+mANAehuelABHZcArEWG7JItiH2pLIAQIWxGj1XBxx+Y7+rtar1JIN4vpNmhs9S+tCTv+GFa1hHj5N0+3WJpHFWMc5Jl8rB+381SLUPd5tvQoQ47fR9uTzgERni2UJHBBDsWvbwDLN1g05fbx0h8ksPu5i1tzkI1e6RfhlwNAn9jREBfisWiK8wulOGdN4noFUnIM9ULdSfZ/9v9qknEPi8Y2Muk6hU0CldrMaTIXI/xrp9lfpoe/E3Z7S5OqdgLPt+AP9Wvr873l7uolCUMkJXqOeV44RQavtLSvbgYujZIa2gqNgXyqm0mtOp5sXYfoh1wEeU3dAZkue2x/Bwe/2Dt5rmpydtLebenJNmT4wS+Jgl4lQLPdn7mQ+bZ0= root@openssh-server
sshd is listening on port 2222
User/password ssh access is disabled.
[custom-init] No custom files found, skipping...
```

if i try use another PGID & PUID working but server not accept key:

Docker Compose:
```
version: "3.9"
services:
  wordpress:
    networks:
      - blackhole
    hostname: openssh-server
    container_name: openssh-server
    restart: unless-stopped
    image: lscr.io/linuxserver/openssh-server:latest
    ports:
      - "2222:2222"
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Rome
      - USER_NAME=www-data
    volumes:
      - /mnt/storage/openssh-server/config:/config
      - /mnt/storage/www-data/:/www-data/

networks:
  blackhole:
    name: container-net
    external: true
```

Docker Log:
```
[migrations] started
[migrations] no migrations found
groupmod: group 'www-data' already exists
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1001
User GID:    1001
───────────────────────────────────────
Linuxserver.io version: 9.7_p1-r4-ls179
Build-date: 2024-12-01T18:53:35+00:00
───────────────────────────────────────
    
User name is set to www-data
sudo is disabled.
ssh-keygen: generating new host keys: RSA ECDSA ED25519 
SSH host public key(s):
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNgS4rePrIpw+uygy69sltdCQdXTzDtVujxBWA+wk/JY9lYmlDzu1KiV/GW1VFA5wC4AJTprxdJmnOAwDSaBamo= root@openssh-server
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAueSTsWJbt0ku3byZZ8iKqWhMpvVSfy14m7jDP0zJN6 root@openssh-server
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXmqMpNt9jtEND7PRyEvQJqZdLUMCrhs+iuUESeFskdjfqvpQH5hFRuIRX/wnct1HJn+aOKhpyvVWuRvlR/GhPqbHyMhHJjavwj4+uZ4hz2QBfxaqu6p6mhYurbFfHDly1ob+mANAehuelABHZcArEWG7JItiH2pLIAQIWxGj1XBxx+Y7+rtar1JIN4vpNmhs9S+tCTv+GFa1hHj5N0+3WJpHFWMc5Jl8rB+381SLUPd5tvQoQ47fR9uTzgERni2UJHBBDsWvbwDLN1g05fbx0h8ksPu5i1tzkI1e6RfhlwNAn9jREBfisWiK8wulOGdN4noFUnIM9ULdSfZ/9v9qknEPi8Y2Muk6hU0CldrMaTIXI/xrp9lfpoe/E3Z7S5OqdgLPt+AP9Wvr873l7uolCUMkJXqOeV44RQavtLSvbgYujZIa2gqNgXyqm0mtOp5sXYfoh1wEeU3dAZkue2x/Bwe/2Dt5rmpydtLebenJNmT4wS+Jgl4lQLPdn7mQ+bZ0= root@openssh-server
sshd is listening on port 2222
User/password ssh access is disabled.
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

SSH Login:
```
~/Sites > ssh -i ./ssh_host_ecdsa_key.pub -p 2222 www-data@10.10.2.8
The authenticity of host '[10.10.2.8]:2222 ([10.10.2.8]:2222)' can't be established.
ECDSA key fingerprint is SHA256:2WbvwKP2gwvTnafBYPbb2U0YPpzJNqeuUhxpKsJ9JFI.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[10.10.2.8]:2222' (ECDSA) to the list of known hosts.
www-data@10.10.2.8: Permission denied (publickey,keyboard-interactive).
```

SSH Server Log:
```
2024-12-03 13:22:18.144002597  Server listening on 0.0.0.0 port 2222.
2024-12-03 13:22:18.144039093  Server listening on :: port 2222.
2024-12-03 13:22:18.147695012  Connection to localhost (127.0.0.1) 2222 port [tcp/*] succeeded!
2024-12-03 13:22:18.155497924  Connection closed by 127.0.0.1 port 45438
2024-12-03 13:23:36.276623481  Connection closed by 172.20.1.69 port 51667 [preauth]
2024-12-03 13:24:00.468866101  Connection closed by authenticating user www-data 172.20.1.69 port 51677 [preauth]
```

**Comment by thespad** [comment]
So the TL;DR is that as www-data is an existing group we can't rename the abc group to that name, so it ends up changing the abc GID to 1001 and assigning that to the user instead.

It might be possible to change things so that in those cases where it's not an existing user but is an existing group we can handle it with a usermod -g. Can you open a new issue with your details and I'll try and find time to take a look at it.

**Comment by antwal** [comment]
> So the TL;DR is that as www-data is an existing group we can't rename the abc group to that name, so it ends up changing the abc GID to 1001 and assigning that to the user instead.
> 
> It might be possible to change things so that in those cases where it's not an existing user but is an existing group we can handle it with a usermod -g. Can you open a new issue with your details and I'll try and find time to take a look at it.

in the second example, where it works because it doesn't recognize the key and continues to give access denied?

**Comment by thespad** [comment]
Not sure, should be looking at the same authorized_keys list in both cases.

Though FWIW in your use case you probably don't *need* to use `www-data` as the username, as long as the UID/GID are correct, which might get you around the problem.

**Comment by antwal** [comment]
then I open a new ticket, 

docker compose:
```
version: "3.9"
services:
  wordpress:
    networks:
      - blackhole
    hostname: openssh-server
    container_name: openssh-server
    restart: unless-stopped
    image: lscr.io/linuxserver/openssh-server:latest
    ports:
      - "2222:2222"
    environment:
      - PUID=1001
      - PGID=33
      - TZ=Europe/Rome
      - USER_NAME=wwwuser
    volumes:
      - /mnt/storage/openssh-server/config:/config
      - /mnt/storage/www-data/:/www-data/

networks:
  blackhole:
    name: container-net
    external: true
```

container log:
```
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1001
User GID:    33
───────────────────────────────────────
Linuxserver.io version: 9.7_p1-r4-ls179
Build-date: 2024-12-01T18:53:35+00:00
───────────────────────────────────────
    
User name is set to wwwuser
sudo is disabled.
ssh-keygen: generating new host keys: RSA ECDSA ED25519 
SSH host public key(s):
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLWIvprZYGuuKAXr+EBePLnepStMux5tOonK7IfrGy4YZjwgULMVFcQEFMj0ajpLrj/SgTtugXCcIsJLcCGki5Y= root@openssh-server
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGboyWweV9oqgKqQKjkoNAjd1FIqjxvx8zZEdwCsGRZM root@openssh-server
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDApM/Mw4Urct8HseYdBecKGnbaBf6WMDJei4omv7CVAv8f5Liep6/P3kXMBZmvVgdl4w+48dSw0G6jblzYexWLMl1AksCDCVm+NJbi1o3BLF85YF0XkUhLkaLxlIqCmb5xATxWBi8yNay8PEsb41MX1XWkuFzalv6izGlE//Z48NW07+BqZK2TEvEPMOF1tr/SeYgTxLHfZql5lJMajBauGu4WPHdrbFJlWcX+bywbQeXi8QKqFi/2UExZIRobEWyIPc+8xRcyBJHEQrIMiGHgJHRJQ3WLFftVEc/zRP6QOzNJH+d9CfZtByh8j5UwS2eG/QEWXzcnYEzY2PXb9AvbPwgZosZsAqNB1XDCdsMCUo31di9wZGrlLZnl/98uTKKHcNQ4HOuyR1+YAWyBGq3BW7XiNOqC9/HGXYvEu9E8n3y6qCloLzLLN8LsCn0opiLGrGVnEAp229M/AsMH55WltMJMGcW/NWKSnwEp0nNPbk8NCeJEH9jA1ivBYL+2RX8= root@openssh-server
sshd is listening on port 2222
User/password ssh access is disabled.
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

list of ssh keys:
```
root@antwal-server:/mnt/storage/openssh-server/config/ssh_host_keys# ls -al
totale 32
drwxr-xr-x 2 1001 www-data 4096  3 dic 15.42 .
drwxr-xr-x 6 1001 www-data 4096  3 dic 15.42 ..
-rw------- 1 1001 www-data  513  3 dic 15.42 ssh_host_ecdsa_key
-rw-r--r-- 1 1001 www-data  181  3 dic 15.42 ssh_host_ecdsa_key.pub
-rw------- 1 1001 www-data  411  3 dic 15.42 ssh_host_ed25519_key
-rw-r--r-- 1 1001 www-data  101  3 dic 15.42 ssh_host_ed25519_key.pub
-rw------- 1 1001 www-data 2602  3 dic 15.42 ssh_host_rsa_key
-rw-r--r-- 1 1001 www-data  573  3 dic 15.42 ssh_host_rsa_key.pub
```

rsa key pub:
```
root@antwal-server:/mnt/storage/openssh-server/config/ssh_host_keys# cat ssh_host_rsa_key.pub 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDApM/Mw4Urct8HseYdBecKGnbaBf6WMDJei4omv7CVAv8f5Liep6/P3kXMBZmvVgdl4w+48dSw0G6jblzYexWLMl1AksCDCVm+NJbi1o3BLF85YF0XkUhLkaLxlIqCmb5xATxWBi8yNay8PEsb41MX1XWkuFzalv6izGlE//Z48NW07+BqZK2TEvEPMOF1tr/SeYgTxLHfZql5lJMajBauGu4WPHdrbFJlWcX+bywbQeXi8QKqFi/2UExZIRobEWyIPc+8xRcyBJHEQrIMiGHgJHRJQ3WLFftVEc/zRP6QOzNJH+d9CfZtByh8j5UwS2eG/QEWXzcnYEzY2PXb9AvbPwgZosZsAqNB1XDCdsMCUo31di9wZGrlLZnl/98uTKKHcNQ4HOuyR1+YAWyBGq3BW7XiNOqC9/HGXYvEu9E8n3y6qCloLzLLN8LsCn0opiLGrGVnEAp229M/AsMH55WltMJMGcW/NWKSnwEp0nNPbk8NCeJEH9jA1ivBYL+2RX8= root@openssh-server
```

ssh login:
```
~/Sites > ssh -i ./ssh_host_rsa_key.pub -p 2222 wwwuser@10.10.2.8
The authenticity of host '[10.10.2.8]:2222 ([10.10.2.8]:2222)' can't be established.
ECDSA key fingerprint is SHA256:domh71Fuv+pww9+I3yPHU6wuDXUKS+lDCd7mkMppVyI.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[10.10.2.8]:2222' (ECDSA) to the list of known hosts.
wwwuser@10.10.2.8: Permission denied (publickey,keyboard-interactive).
```

openssh-server log:
```
root@antwal-server:/mnt/storage/openssh-server/config/logs/openssh# cat current 
2024-12-03 15:42:49.647437166  Server listening on 0.0.0.0 port 2222.
2024-12-03 15:42:49.647477364  Server listening on :: port 2222.
2024-12-03 15:42:49.651024250  Connection to localhost (127.0.0.1) 2222 port [tcp/*] succeeded!
2024-12-03 15:42:49.658591219  Connection closed by 127.0.0.1 port 40894
2024-12-03 15:46:58.628288950  Connection closed by 172.20.1.69 port 55844 [preauth]
2024-12-03 15:47:39.399435862  Connection closed by authenticating user wwwuser 172.20.1.69 port 55864 [preauth]
```

**Comment by antwal** [comment]
solved after several tests, now it seems to work but with username/password, using the key it doesn't work

this way you have read and write permissions like www-data:www-data (33:33) and in the main server the files appear with the correct permissions

docker compose:
```
version: "3.9"
services:
  wordpress:
    networks:
      - blackhole
    hostname: openssh-server
    container_name: openssh-server
    restart: unless-stopped
    image: lscr.io/linuxserver/openssh-server:latest
    ports:
      - "2222:2222"
    environment:
      - PUID=33
      - PGID=33
      - TZ=Europe/Rome
      - USER_NAME=www-user
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=password
    volumes:
      - /mnt/storage/openssh-server/config:/config
      - /mnt/storage/www-data/:/www-data/

networks:
  blackhole:
    name: container-net
    external: true
```

container log:
```
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    33
User GID:    33
───────────────────────────────────────
Linuxserver.io version: 9.7_p1-r4-ls179
Build-date: 2024-12-01T18:53:35+00:00
───────────────────────────────────────
    
User name is set to www-user
sudo is disabled.
SSH host public key(s):
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLWIvprZYGuuKAXr+EBePLnepStMux5tOonK7IfrGy4YZjwgULMVFcQEFMj0ajpLrj/SgTtugXCcIsJLcCGki5Y= root@openssh-server
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGboyWweV9oqgKqQKjkoNAjd1FIqjxvx8zZEdwCsGRZM root@openssh-server
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDApM/Mw4Urct8HseYdBecKGnbaBf6WMDJei4omv7CVAv8f5Liep6/P3kXMBZmvVgdl4w+48dSw0G6jblzYexWLMl1AksCDCVm+NJbi1o3BLF85YF0XkUhLkaLxlIqCmb5xATxWBi8yNay8PEsb41MX1XWkuFzalv6izGlE//Z48NW07+BqZK2TEvEPMOF1tr/SeYgTxLHfZql5lJMajBauGu4WPHdrbFJlWcX+bywbQeXi8QKqFi/2UExZIRobEWyIPc+8xRcyBJHEQrIMiGHgJHRJQ3WLFftVEc/zRP6QOzNJH+d9CfZtByh8j5UwS2eG/QEWXzcnYEzY2PXb9AvbPwgZosZsAqNB1XDCdsMCUo31di9wZGrlLZnl/98uTKKHcNQ4HOuyR1+YAWyBGq3BW7XiNOqC9/HGXYvEu9E8n3y6qCloLzLLN8LsCn0opiLGrGVnEAp229M/AsMH55WltMJMGcW/NWKSnwEp0nNPbk8NCeJEH9jA1ivBYL+2RX8= root@openssh-server
sshd is listening on port 2222
User/password ssh access is enabled.
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

/etc/passwd file:
```
root@openssh-server:/# cat /etc/passwd
root:x:0:0:root:/root:/bin/sh
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/mail:/sbin/nologin
news:x:9:13:news:/usr/lib/news:/sbin/nologin
uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
ftp:x:21:21::/var/lib/ftp:/sbin/nologin
sshd:x:22:22:sshd:/dev/null:/sbin/nologin
games:x:35:35:games:/usr/games:/sbin/nologin
ntp:x:123:123:NTP:/var/empty:/sbin/nologin
guest:x:405:1000:guest:/dev/null:/sbin/nologin
nobody:x:65534:65534:nobody:/:/sbin/nologin
klogd:x:100:101:klogd:/dev/null:/sbin/nologin
www-user:x:33:33::/config:/bin/bash
```
